Maxon:
  config_run_sdo_verify_timeout: 50000
  print_debug_messages: true
  use_raw_commands: false #vorher false
  drive_state_change_min_timeout: 2000
  drive_state_change_max_timeout: 1000000
  min_number_of_successful_target_state_readings: 5


Reading:
  force_append_equal_error: true
  force_append_equal_fault: false
  error_storage_capacity: 100
  fault_storage_capacity: 100


X-Hardware-Variations:
  config-24V: &24V
    working_voltage: 24
    torque_constant: 0.0395
    nominal_current: 9.8

  config-48V: &48V
    working_voltage: 48
    torque_constant: 0.0624
    nominal_current: 5.8

  pid-initial: &pidInitial
    position_p_gain: 25.91 # ??? A/rad ???
    position_i_gain: 1052.81 # ??? A/(rad*s) ???
    position_d_gain: 0.208 # ??? A*s/rad ???

    velocity_p_gain: 0.145
    velocity_i_gain: 9.153

    current_p_gain: 8.426858 # TODO
    current_i_gain: 1069.9972 # TODO

  pid-epos-studio: &pidEposStudio
    position_p_gain: 25941.524
    position_i_gain: 1052310.974
    position_d_gain: 207.688

    velocity_p_gain: 147.082
    velocity_i_gain: 9266.162

    current_p_gain: 8.426858 # TODO
    current_i_gain: 1069.9972 # TODO

  pid-github: &pidGithub
    position_p_gain: 1851.991
    position_i_gain: 14728.264
    position_d_gain: 18.556

    velocity_p_gain: 23.675
    velocity_i_gain: 2372.879

    current_p_gain: 2528.017
    current_i_gain: 9540.744


Hardware:
  <<: *24V
  <<: *pidEposStudio

  mode_of_operation:
  - CyclicSynchronousTorqueMode
  - CyclicSynchronousPositionMode
  - CyclicSynchronousVelocityMode
  position_encoder_resolution: 4096
  gear_ratio: [62, 1]
  motor_constant: 1.0
  pole_pairs: 8 # From Epos Studio
  speed_constant: 242
  max_current: 24
  min_position: 0
  max_position: 0 # 0 = Disable checks
  max_profile_velocity: 628
  quick_stop_decel: 1000
  profile_decel: 1000
  follow_error_window: 4000000000
