ethercat_master:
  time_step:                          0.02
  update_rate_too_low_warn_threshold: 50

ethercat_devices:
  - type:               Maxon
    name:               Maxon
    configuration_file: device_configurations/maxon.yaml
    ethercat_bus:       enp2s0
    ethercat_address:   1
